/* ============================================================
   RIGWATCH - DATABASE SETUP
   PostgreSQL 12 or later

   Run this file once before running any of the three project
   scripts. It creates the tables, loads the CSV files, and
   builds the indexes the analysis depends on.

   Why this file exists:
   The original script had no table definitions at all. It
   assumed the tables were already sitting in a database
   somewhere. That makes the work impossible for anyone else
   to reproduce, and it hid a real problem, which is that
   cost_usd was being stored as text and cast to FLOAT inside
   every query that touched it. Money should never live in a
   FLOAT column, so it is NUMERIC here.
   ============================================================ */


/* ------------------------------------------------------------
   1. CLEAN SLATE
   Dropping in reverse dependency order so re-running the file
   never fails halfway through.
------------------------------------------------------------ */

DROP VIEW  IF EXISTS v_asset_reliability CASCADE;
DROP TABLE IF EXISTS maintenance CASCADE;
DROP TABLE IF EXISTS production  CASCADE;
DROP TABLE IF EXISTS emissions   CASCADE;


/* ------------------------------------------------------------
   2. MAINTENANCE

   One row per maintenance event. 3,000 events.

   The source CSV has no unique identifier for an event, which
   means there is no safe way to count distinct failures once
   the table is joined to anything else. A surrogate key fixes
   that, and it is the single change that makes the corrected
   queries in project 03 possible.
------------------------------------------------------------ */

CREATE TABLE maintenance (
    maintenance_id    BIGSERIAL PRIMARY KEY,
    asset_id          TEXT        NOT NULL,
    maintenance_date  DATE        NOT NULL,
    cost_usd          NUMERIC(14,2),
    failure_type      TEXT,
    downtime_hours    INTEGER
);


/* ------------------------------------------------------------
   3. PRODUCTION

   Daily production readings by well. 5,000 rows.

   The CSV column is called "date". That is a type name in
   SQL, so it has been renamed to production_date. It reads
   better and it stops the query editor from colouring it as
   a keyword.
------------------------------------------------------------ */

CREATE TABLE production (
    well_id                 TEXT    NOT NULL,
    production_date         DATE    NOT NULL,
    oil_production_barrels  INTEGER,
    gas_production_mcf      INTEGER,
    water_cut_pct           NUMERIC(6,2),
    pressure_psi            INTEGER,
    temperature_c           INTEGER
);


/* ------------------------------------------------------------
   4. EMISSIONS

   Environmental readings by asset. 3,000 rows.
   Covers wells, pipelines and refineries, so it is the only
   one of the three tables that lines up with the full range
   of asset IDs found in maintenance.
------------------------------------------------------------ */

CREATE TABLE emissions (
    asset_id                TEXT    NOT NULL,
    co2_tons                NUMERIC(12,2),
    methane_leakage_tons    NUMERIC(12,2),
    energy_consumption_mwh  NUMERIC(14,2),
    reading_date            DATE
);


/* ------------------------------------------------------------
   5. LOAD THE DATA

   These are psql client side commands. Run them from psql
   with your working directory set to the repository root.

   If you are using pgAdmin or DBeaver instead, use the import
   wizard and point it at the same three files.

   The maintenance load names its columns explicitly because
   maintenance_id is generated by the database and is not in
   the CSV.
------------------------------------------------------------ */

-- \copy maintenance (asset_id, maintenance_date, cost_usd, failure_type, downtime_hours) FROM 'data/maintenance.csv' WITH (FORMAT csv, HEADER true);
-- \copy production FROM 'data/production.csv' WITH (FORMAT csv, HEADER true);
-- \copy emissions  FROM 'data/emissions.csv'  WITH (FORMAT csv, HEADER true);


/* ------------------------------------------------------------
   6. INDEXES

   Every query in all three projects either groups by asset or
   joins on it, so these three indexes cover the whole
   workload.
------------------------------------------------------------ */

CREATE INDEX idx_maintenance_asset ON maintenance (asset_id);
CREATE INDEX idx_production_well   ON production  (well_id);
CREATE INDEX idx_emissions_asset   ON emissions   (asset_id);


/* ------------------------------------------------------------
   7. ASSET CLASS HELPER

   Asset IDs carry their type in the first three characters.
   WEL is a well, PIP is a pipeline, REF is a refinery.

   This matters more than it looks. The production table only
   holds wells, so any join from maintenance to production
   will silently return nothing for pipelines and refineries.
   Without labelling the asset class, a refinery that cost
   half a million dollars to maintain shows up as an asset
   with high spend and zero production, which is wrong. It
   produces no barrels because it is a refinery, not because
   it is failing.
------------------------------------------------------------ */

CREATE OR REPLACE FUNCTION asset_class(p_asset_id TEXT)
RETURNS TEXT AS $$
    SELECT CASE LEFT(p_asset_id, 3)
             WHEN 'WEL' THEN 'Well'
             WHEN 'PIP' THEN 'Pipeline'
             WHEN 'REF' THEN 'Refinery'
             ELSE 'Unknown'
           END;
$$ LANGUAGE SQL IMMUTABLE;


/* ------------------------------------------------------------
   8. SANITY CHECKS

   Run these after loading. If any of them look wrong, stop
   and fix the load before running the analysis.
------------------------------------------------------------ */

-- Row counts. Expect 3000, 5000, 3000.
SELECT 'maintenance' AS table_name, COUNT(*) AS row_count FROM maintenance
UNION ALL
SELECT 'production',  COUNT(*) FROM production
UNION ALL
SELECT 'emissions',   COUNT(*) FROM emissions;


-- How the maintenance events split across asset types.
SELECT
    asset_class(asset_id)    AS asset_type,
    COUNT(*)                 AS maintenance_events,
    COUNT(DISTINCT asset_id) AS distinct_assets
FROM maintenance
GROUP BY 1
ORDER BY maintenance_events DESC;


-- How many maintenance assets can actually be matched to
-- production. Anything below 100 percent is the join key
-- problem described in every project README.
SELECT
    asset_class(m.asset_id)    AS asset_type,
    COUNT(DISTINCT m.asset_id) AS assets_in_maintenance,
    COUNT(DISTINCT p.well_id)  AS assets_found_in_production
FROM maintenance m
LEFT JOIN production p ON m.asset_id = p.well_id
GROUP BY 1
ORDER BY 1;


-- Duplicate check. If either average is above 1, any query
-- that joins straight onto these tables will double count.
SELECT
    'production rows per well' AS check_name,
    ROUND(AVG(row_count), 2)   AS average_rows,
    MAX(row_count)             AS worst_case
FROM (SELECT well_id, COUNT(*) AS row_count FROM production GROUP BY well_id) x
UNION ALL
SELECT
    'emissions rows per asset',
    ROUND(AVG(row_count), 2),
    MAX(row_count)
FROM (SELECT asset_id, COUNT(*) AS row_count FROM emissions GROUP BY asset_id) y;


-- Nulls and impossible values.
SELECT
    COUNT(*) FILTER (WHERE cost_usd IS NULL)       AS null_cost,
    COUNT(*) FILTER (WHERE cost_usd < 0)           AS negative_cost,
    COUNT(*) FILTER (WHERE downtime_hours IS NULL) AS null_downtime,
    COUNT(*) FILTER (WHERE downtime_hours < 0)     AS negative_downtime,
    COUNT(*) FILTER (WHERE failure_type IS NULL)   AS null_failure_type,
    MIN(maintenance_date)                          AS earliest_event,
    MAX(maintenance_date)                          AS latest_event
FROM maintenance;
